variables:
  GIT_SUBMODULE_STRATEGY: recursive

prove-wrapper:
  image: etalian/skywater-pdk
  before_script:
    - git clone https://github.com/mattvenn/multi_project_tools /tmp/multi_project_tools
    - pip3 install PyYAML
    # multi_tools does not support relative paths, therefore we have to force absolute ones
    - ln -s "${PWD}" /tmp/bfloat16_fma
  script:
    - ( cd /tmp/multi_project_tools/ && ./multi_tool.py --config /tmp/bfloat16_fma/projects.yaml --prove-wrapper --force-delete )

test-module:
  image: etalian/skywater-pdk
  before_script:
    - git clone https://github.com/mattvenn/multi_project_tools /tmp/multi_project_tools
    - git clone https://github.com/ucb-bar/berkeley-softfloat-3 /tmp/berkeley-softfloat-3
    - make -C /tmp/berkeley-softfloat-3/build/Linux-x86_64-GCC
    - git clone https://github.com/ucb-bar/berkeley-testfloat-3 /tmp/berkeley-testfloat-3
    - make -C /tmp/berkeley-testfloat-3/build/Linux-x86_64-GCC
    - ln -s /tmp/berkeley-testfloat-3/build/Linux-x86_64-GCC/testfloat_gen /usr/local/bin
    - pip3 install PyYAML
    # multi_tools does not support relative paths, therefore we have to force absolute ones
    - ln -s "${PWD}" /tmp/bfloat16_fma
  script:
    - ( cd /tmp/multi_project_tools/ && ./multi_tool.py --config /tmp/bfloat16_fma/projects.yaml --test-module --force-delete )

test-caravel:
  image: etalian/skywater-pdk
  before_script:
    - git clone https://github.com/mattvenn/multi_project_tools /tmp/multi_project_tools
    - git clone -b mpw-two-c https://github.com/efabless/caravel_user_project /tmp/caravel_user_project
    - ( cd /tmp/caravel_user_project && make install )
    # TODO: do we actually need to install netgen from git?
    - yum install -y python3-devel
    - pip3 install gdspy PyYAML cocotb
    # multi_tools does not support relative paths, therefore we have to force absolute ones
    - ln -s "${PWD}" /tmp/bfloat16_fma
  script:
    - ( cd /tmp/multi_project_tools/ && ./multi_tool.py --config /tmp/bfloat16_fma/projects.yaml --test-caravel --force-delete )
